name: farm_buddy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.3
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  image: ^4.1.3
  tflite_flutter: ^0.11.0

dependency_overrides:
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image_model.tflite
    - assets/ann_model.tflite
